# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/maket_op.xdc

# IP: ip/fifo_4k/fifo_4k.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_4k || ORIG_REF_NAME==fifo_4k} -quiet] -quiet
